//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiBandApp.Strings.en_US {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdatesHistoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdatesHistoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiBandApp.Strings.en_US.UpdatesHistoryResources", typeof(UpdatesHistoryResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguageMsg_Text {
            get {
                return ResourceManager.GetString("ChangeLanguageMsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        internal static string CreateFormBtn_Content {
            get {
                return ResourceManager.GetString("CreateFormBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string CreateFormContent_Header {
            get {
                return ResourceManager.GetString("CreateFormContent.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task content.
        /// </summary>
        internal static string CreateFormContent_PlaceholderText {
            get {
                return ResourceManager.GetString("CreateFormContent.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CreateFormTitle_Header {
            get {
                return ResourceManager.GetString("CreateFormTitle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task title.
        /// </summary>
        internal static string CreateFormTitle_PlaceholderText {
            get {
                return ResourceManager.GetString("CreateFormTitle.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Creation.
        /// </summary>
        internal static string CreateMenuHeader_Text {
            get {
                return ResourceManager.GetString("CreateMenuHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        internal static string EditFormBtn_Content {
            get {
                return ResourceManager.GetString("EditFormBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string EditFormContent_Header {
            get {
                return ResourceManager.GetString("EditFormContent.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task content here.
        /// </summary>
        internal static string EditFormContent_PlaceholderText {
            get {
                return ResourceManager.GetString("EditFormContent.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EditFormTitle_Header {
            get {
                return ResourceManager.GetString("EditFormTitle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task title here.
        /// </summary>
        internal static string EditFormTitle_PlaceholderText {
            get {
                return ResourceManager.GetString("EditFormTitle.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Edit.
        /// </summary>
        internal static string EditTaskHeader_Text {
            get {
                return ResourceManager.GetString("EditTaskHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageBox_Header {
            get {
                return ResourceManager.GetString("LanguageBox.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string MainHeader_Text {
            get {
                return ResourceManager.GetString("MainHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string MenuActive_Text {
            get {
                return ResourceManager.GetString("MenuActive.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string MenuAll_Text {
            get {
                return ResourceManager.GetString("MenuAll.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string MenuFinished_Text {
            get {
                return ResourceManager.GetString("MenuFinished.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string NewTaskBtn_Content {
            get {
                return ResourceManager.GetString("NewTaskBtn.Content", resourceCulture);
            }
        }
    }
}
